### ISSUE TITLE
Container crashes when trying to connect with WinSCP

### ISSUE THREAD

**Issue by stuntguy3000** [garethflowers/docker-ftp-server#27]
Hi,

I've set this up and am trying to use it for the first time. I am finding an issue where after connecting with WinSCP to begin using the server, it crashes and burns (and the container stops running)

After authentication,
![image](https://user-images.githubusercontent.com/1522389/178495927-a7e4db0b-cb18-41ab-91c4-36bfa4ce01ce.png)

Logs don't reveal much either. This is all that appears in Docker console before it stops running/crashes.
![image](https://user-images.githubusercontent.com/1522389/178496281-56a31a35-be88-4c56-b33a-2b3c42f5d10f.png)

I've attempted to break into the container to grab more information, but I've hit a roadblock.
```
docker exec a89d0dd630d2 bash
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "bash": executable file not found in $PATH: unknown
```

Appreciate your help!

**Comment by Raptime** [comment]
I think the issue is this line in the config:
ftp_data_port=21

it's trying to bind the data port on the same port used for control. Commenting out this line should fix the issue.
