### ISSUE TITLE
Set user ID

### ISSUE THREAD

**Issue by WetenSchaap** [garethflowers/docker-ftp-server#35]
It would be nice if it is possible to be able set the user UID in the docker command, so created files have the correct permissions.

**Comment by derMart** [comment]
Judging from https://github.com/garethflowers/docker-ftp-server/blob/1664796bc6a26efb0205813cce9bafb376af11b4/src/docker-entrypoint.sh#L13 this might be possible by specifying the UID env variable, haven't tested this though.

**Comment by garethflowers** [comment]
Resolved by e5234ff2d4dfa43f7db4d449e0a8464b5e5c1083 and 056f99a7ad759582c037136cfe95e625eb45e766.
