### ISSUE TITLE
vsftpd.conf in a persistent volume

### ISSUE THREAD

**Issue by stefore** [garethflowers/docker-ftp-server#42]
Hi,
is it possible to mount the vsftpd.conf file in a volume (in order to change some parameters) ?

**Comment by lociii** [comment]
Would also love to see this as `pasv_address=0.0.0.0` results in an `Server sent passive reply with unroutable address. Using server address instead.` for me when accessing the FTP with port forwarding behind a NAT.

**Comment by bill88t** [comment]
You can do it just fine, but the file needs to be owned by root.

**Comment by stefore** [comment]
it works !  thanks you bill88t  :)
