### ISSUE TITLE
tzdata missing 

### ISSUE THREAD

**Issue by bejaranoo** [garethflowers/docker-ftp-server#62]
fixed by issuing:
`apk add --no-cache tzdata`
but obviously it will be lost when you restart the container, any permanent solution would be appreciated

**Comment by scolbeck** [comment]
You could set the container's timezone to match the host via these volume mappings.  Here is an example for Docker compose:
```
    volumes:
      - '/data:/home/user'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
```
