### ISSUE TITLE
Opening a lot of ports. Why?

### ISSUE THREAD

**Issue by Feriman22** [garethflowers/docker-ftp-server#75]
Hi,

There are a lot of ports opened by docker compose (and docker run), specifically these:

```
- '20-21:20-21/tcp'
- '40000-40009:40000-40009/tcp'
```

However, to connect to the FTP server, it is sufficient to open TCP port 21. What is the purpose/meaning of the other ports?

Edit: I tested it in bridge network mode, and it works as expected. So only the 21 TCP port is required.

Thanks,
Feriman

**Comment by dnagy** [comment]
They are needed for passive mode. You can take a look at the configuration file for details: https://github.com/garethflowers/docker-ftp-server/blob/main/src/vsftpd.conf
If you don't intend to use passive mode, than you don't have to open those ports.

**Comment by Feriman22** [comment]
I have created a pull request for that:
https://github.com/garethflowers/docker-ftp-server/pull/77
