### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rain2307** [garethflowers/docker-ftp-server#83]
It’s a waste of time. I tried many times and still cannot get it work.
I recommend Dropbear. 

1. Cannot list directory: you have to edit /etc/vsftpd.conf and change 0.0.0.0 -> you ip.
2. set FTP_USER=xxx and mount /data:/home/xxx : WinSCP shows empty direcotry. tried many times.
3. the docker status shows 'unhealthy', check the log "xxx user already exists'.

I'm using openwrt.

**Comment by TheFax** [comment]
Try [This repo](https://github.com/TheFax/sbc_ftp_server), if you want.
